import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => { localStorage.setItem('pocket-ledger-pwa-install-prompt-seen', 'true') })
})

test('mobile back closes the add menu and record sheet before returning Home', async ({ page, isMobile }) => {
  test.skip(!isMobile)
  await page.goto('/app?vault-preview')
  await page.getByRole('button', { name: 'Ledger', exact: true }).last().click()
  await expect(page).toHaveURL(/transactions/)
  await page.getByRole('button', { name: 'Add entry', exact: true }).click()
  await expect(page.getByRole('menu')).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('menu')).toBeHidden()
  await expect(page).toHaveURL(/transactions/)
  await page.getByRole('button', { name: 'Add entry', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Record spent' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page).toHaveURL(/transactions/)
  await page.goBack()
  await expect(page).toHaveURL(/\/app\?vault-preview$/)
})

test('direct mobile Paths link backs to Home', async ({ page, isMobile }) => {
  test.skip(!isMobile)
  await page.goto('/app/goals?vault-preview')
  await expect(page.getByRole('heading', { name: 'Your paths.' })).toBeVisible()
  await page.goBack()
  await expect(page).toHaveURL(/\/app\?vault-preview$/)
})

test('recap opens from existing Story layout and closes with Back', async ({ page, isMobile }) => {
  if (!isMobile) await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/app/reports?vault-preview')
  await page.getByRole('button', { name: 'Your latest weekly recap' }).filter({ visible: true }).click()
  await expect(page.getByRole('dialog', { name: 'Your Sunday recap' })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCSS('opacity', '1')
  await page.screenshot({ path: `test-results/weekly-recap-${isMobile ? 'mobile' : 'desktop'}.png` })
  await page.goBack()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page).toHaveURL(/reports/)
})

test('receivables support partial payment, write-off and recovery in preview', async ({ page, isMobile }) => {
  if (!isMobile) await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/app/goals?vault-preview')
  await page.getByRole('button', { name: 'Add receivable' }).filter({ visible: true }).click()
  await page.getByLabel('Person', { exact: true }).fill('Ali')
  await page.getByLabel('Amount owed', { exact: true }).fill('10000')
  await page.getByRole('button', { name: 'Save receivable', exact: true }).click()
  await page.getByRole('button', { name: /Ali.*10,000/ }).filter({ visible: true }).click()
  await page.getByRole('button', { name: 'Record repayment', exact: true }).click()
  await page.getByLabel('Amount received', { exact: true }).fill('2000')
  await page.getByRole('button', { name: 'Record received', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('2,000 repaid')
  await page.getByRole('button', { name: 'Write off remaining amount', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm write-off', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('8,000 written off')
  await page.getByRole('button', { name: 'Record recovery', exact: true }).click()
  await page.getByLabel('Amount received', { exact: true }).fill('1000')
  await page.getByRole('button', { name: 'Record received', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('7,000 written off')
})

test('retired features are absent from Home and Plan', async ({ page, isMobile }) => {
  if (!isMobile) await page.setViewportSize({ width: 1440, height: 1000 })
  for (const path of ['/app?vault-preview', '/app/budgets?vault-preview']) {
    await page.goto(path)
    await expect(page.locator('body')).not.toContainText('Safe today')
    await expect(page.getByText('Safe to spend today', { exact: false })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Cool-off', exact: true })).toHaveCount(0)
    await expect(page.getByRole('tab', { name: 'Quests', exact: true })).toHaveCount(0)
  }
})


test('delete toast has an icon-only Undo that restores the entry', async ({ page, isMobile }) => {
  test.skip(!isMobile)
  await page.goto('/app/transactions?vault-preview')
  const row = page.locator('.mobile-page-content .vault-row').first()
  const title = await row.locator('.vault-row-title').innerText()
  const originalCount = await page.locator('.mobile-page-content .vault-row-title').filter({ hasText: title }).count()
  await row.click()
  await page.getByRole('button', { name: 'Delete', exact: true }).filter({ visible: true }).click()
  const toast = page.getByRole('status').filter({ hasText: 'Transaction deleted' })
  await expect(toast).toBeVisible()
  const undo = toast.getByRole('button', { name: 'Undo', exact: true })
  await expect(undo).toHaveText('')
  await expect(toast).toHaveCSS('opacity', '1')
  await page.screenshot({ path: 'test-results/undo-toast-mobile.png' })
  await undo.click()
  await expect(page.locator('.mobile-page-content .vault-row-title').filter({ hasText: title })).toHaveCount(originalCount)
  await expect(page.getByRole('status')).toContainText('Transaction restored')
})


test('Sunday recap appears once and remains accessible from Story', async ({ page, isMobile }) => {
  test.skip(!isMobile)
  await page.clock.install({ time: new Date('2026-09-13T12:00:00') })
  await page.goto('/app?vault-preview')
  const recap = page.getByRole('dialog', { name: 'Your Sunday recap' })
  await expect(recap).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: /Good/ }).first()).toBeVisible()
  await page.clock.runFor(1500)
  await expect(recap).toBeHidden()
  await page.getByRole('button', { name: 'Insights', exact: true }).last().click()
  await page.getByRole('button', { name: 'Your latest weekly recap' }).filter({ visible: true }).click()
  await expect(recap).toBeVisible()
})

test('Paths keeps goal and debt circles aligned on a narrow phone', async ({ page, isMobile }) => {
  test.skip(!isMobile)
  await page.setViewportSize({ width: 360, height: 800 })
  await page.goto('/app/goals?vault-preview')
  await expect(page.locator('.vault-debt-badge').first()).toHaveCSS('width', '48px')
  await expect(page.locator('.vault-ring').first()).toHaveCSS('width', '48px')
  await expect(page.locator('.mobile-page-content')).toBeVisible()
  await page.screenshot({ path: 'test-results/paths-360.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
