import {
  BadgeDollarSign,
  BriefcaseBusiness,
  BusFront,
  CarFront,
  CircleHelp,
  Coffee,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HandHeart,
  HeartPulse,
  HeartHandshake,
  House,
  Landmark,
  Laptop,
  Music,
  Pill,
  Plane,
  ReceiptText,
  Repeat2,
  RotateCcw,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Ticket,
  TrendingUp,
  UtensilsCrossed,
  WalletCards,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { Category, CategoryIconName } from '../types/finance'

export const CATEGORY_COLOR_OPTIONS = [
  { value: '#E2703A', label: 'Clay' },
  { value: '#7C8A6B', label: 'Sage' },
  { value: '#6B7A85', label: 'Slate' },
  { value: '#C79A3E', label: 'Gold' },
  { value: '#B08968', label: 'Sand' },
  { value: '#9B6A7D', label: 'Mauve' },
  { value: '#8A8A3F', label: 'Olive' },
  { value: '#8A7B63', label: 'Taupe' },
] as const

export const CATEGORY_ICON_OPTIONS: Array<{ value: CategoryIconName; label: string; icon: LucideIcon }> = [
  { value: 'home', label: 'Home', icon: House },
  { value: 'dining', label: 'Dining', icon: UtensilsCrossed },
  { value: 'groceries', label: 'Groceries', icon: ShoppingBasket },
  { value: 'coffee', label: 'Coffee', icon: Coffee },
  { value: 'car', label: 'Car', icon: CarFront },
  { value: 'transport', label: 'Transport', icon: BusFront },
  { value: 'fuel', label: 'Fuel', icon: Fuel },
  { value: 'shopping', label: 'Shopping', icon: ShoppingBag },
  { value: 'clothing', label: 'Clothing', icon: Shirt },
  { value: 'health', label: 'Health', icon: HeartPulse },
  { value: 'medicine', label: 'Medicine', icon: Pill },
  { value: 'education', label: 'Education', icon: GraduationCap },
  { value: 'bills', label: 'Bills', icon: ReceiptText },
  { value: 'phone', label: 'Phone', icon: Smartphone },
  { value: 'internet', label: 'Internet', icon: Wifi },
  { value: 'entertainment', label: 'Entertainment', icon: Music },
  { value: 'tickets', label: 'Tickets', icon: Ticket },
  { value: 'work', label: 'Work', icon: BriefcaseBusiness },
  { value: 'gift', label: 'Gift', icon: Gift },
  { value: 'wallet', label: 'Wallet', icon: WalletCards },
  { value: 'bank', label: 'Bank', icon: Landmark },
  { value: 'fitness', label: 'Fitness', icon: Dumbbell },
  { value: 'travel', label: 'Travel', icon: Plane },
  { value: 'grooming', label: 'Grooming', icon: Scissors },
  { value: 'laptop', label: 'Laptop', icon: Laptop },
  { value: 'refund', label: 'Refund', icon: RotateCcw },
  { value: 'salary', label: 'Salary', icon: BadgeDollarSign },
  { value: 'investment', label: 'Investment', icon: TrendingUp },
  { value: 'allowance', label: 'Allowance', icon: HandCoins },
  { value: 'family', label: 'Family', icon: HeartHandshake },
  { value: 'charity', label: 'Charity', icon: HandHeart },
  { value: 'utilities', label: 'Utilities', icon: Zap },
  { value: 'subscription', label: 'Subscription', icon: Repeat2 },
  { value: 'miscellaneous', label: 'Miscellaneous', icon: CircleHelp },
  { value: 'gaming', label: 'Gaming', icon: Gamepad2 },
]

const CATEGORY_PRESENTATIONS: Array<{ match: RegExp; color: string; icon: CategoryIconName }> = [
  { match: /refund|reimburse/i, color: '#7C8A6B', icon: 'refund' },
  { match: /salary|paycheck|wage/i, color: '#7C8A6B', icon: 'salary' },
  { match: /business|freelance|client|computer|laptop|software/i, color: '#7C8A6B', icon: 'laptop' },
  { match: /invest|dividend|profit|return/i, color: '#C79A3E', icon: 'investment' },
  { match: /allowance|pocket money/i, color: '#B08968', icon: 'allowance' },
  { match: /charity|zakat|donation/i, color: '#9B6A7D', icon: 'charity' },
  { match: /subscription|recurring/i, color: '#8A8A3F', icon: 'subscription' },
  { match: /electric|energy|water|utilit/i, color: '#C79A3E', icon: 'utilities' },
  { match: /game|gaming/i, color: '#8A8A3F', icon: 'gaming' },
  { match: /din(e|ing)|food|restaurant/i, color: '#E2703A', icon: 'dining' },
  { match: /fuel|petrol|gas/i, color: '#6B7A85', icon: 'fuel' },
  { match: /transport|bus|train/i, color: '#6B7A85', icon: 'transport' },
  { match: /travel|flight/i, color: '#6B7A85', icon: 'travel' },
  { match: /car|vehicle/i, color: '#6B7A85', icon: 'car' },
  { match: /grocer/i, color: '#7C8A6B', icon: 'groceries' },
  { match: /rent|housing|apartment|mortgage/i, color: '#B08968', icon: 'home' },
  { match: /bill|invoice/i, color: '#B08968', icon: 'bills' },
  { match: /shop/i, color: '#9B6A7D', icon: 'shopping' },
  { match: /cloth/i, color: '#9B6A7D', icon: 'clothing' },
  { match: /health|care|doctor/i, color: '#C79A3E', icon: 'health' },
  { match: /medic|pharmacy/i, color: '#C79A3E', icon: 'medicine' },
  { match: /fun|entertain|music|movie|cinema/i, color: '#8A8A3F', icon: 'entertainment' },
  { match: /mobile|phone/i, color: '#6B7A85', icon: 'phone' },
  { match: /internet|wifi/i, color: '#6B7A85', icon: 'internet' },
  { match: /educat|school|fee/i, color: '#8A7B63', icon: 'education' },
  { match: /work|job|career/i, color: '#7C8A6B', icon: 'work' },
  { match: /family|friend|parent|support/i, color: '#B08968', icon: 'family' },
  { match: /gift/i, color: '#9B6A7D', icon: 'gift' },
  { match: /groom|salon|barber|cutting/i, color: '#8A7B63', icon: 'grooming' },
  { match: /home/i, color: '#B08968', icon: 'home' },
  { match: /misc|other|unexplained/i, color: '#8A7B63', icon: 'miscellaneous' },
]

export function categoryIconForName(name?: CategoryIconName): LucideIcon {
  return CATEGORY_ICON_OPTIONS.find((option) => option.value === name)?.icon ?? WalletCards
}

export function suggestedCategoryIcon(category: Pick<Category, 'name' | 'kind' | 'icon'>): CategoryIconName {
  return category.icon ?? CATEGORY_PRESENTATIONS.find((entry) => entry.match.test(category.name))?.icon ?? (category.kind === 'income' ? 'work' : 'wallet')
}

export function categoryPresentationFor(category: Category) {
  const match = CATEGORY_PRESENTATIONS.find((entry) => entry.match.test(category.name))
  const iconName = suggestedCategoryIcon(category)
  return { color: category.color || match?.color || '#8A7B63', icon: categoryIconForName(iconName), iconName }
}
